server:
  port: 8701

spring:
  application:
    name: bop2-register-center

eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  file: logs/registry.log
